name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  # Étape 1 : Tests pour la branche dev
  test:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest --maxfail=5 --disable-warnings

  # Étape 2 : Build Docker et tests pour la branche staging
  build-and-test:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t your_dockerhub_username/app-backend:staging .
          docker build -f frontend/Dockerfile -t your_dockerhub_username/app-frontend:staging .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push your_dockerhub_username/app-backend:staging
          docker push your_dockerhub_username/app-frontend:staging

      - name: Run integration tests
        run: |
          # Ajouter ici vos tests d'intégration spécifiques à l'application
          echo "Tests d'intégration exécutés."

  # Étape 3 : Build final et déploiement pour la branche main
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker images from staging
        run: |
          docker pull your_dockerhub_username/app-backend:staging
          docker pull your_dockerhub_username/app-frontend:staging

      - name: Tag images as latest
        run: |
          docker tag your_dockerhub_username/app-backend:staging your_dockerhub_username/app-backend:latest
          docker tag your_dockerhub_username/app-frontend:staging your_dockerhub_username/app-frontend:latest

      - name: Push Docker images to main
        run: |
          docker push your_dockerhub_username/app-backend:latest
          docker push your_dockerhub_username/app-frontend:latest

      - name: Deploy to Cloud
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CLOUD_API_KEY }}" \
          -d '{"image":"your_dockerhub_username/app-backend:latest"}' \
          https://your-cloud-platform/api/deploy
