name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest --maxfail=5 --disable-warnings

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t your_dockerhub_username/app-backend:latest .
          docker build -f frontend/Dockerfile -t your_dockerhub_username/app-frontend:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push your_dockerhub_username/app-backend:latest
          docker push your_dockerhub_username/app-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Cloud
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CLOUD_API_KEY }}" \
          -d '{"image":"your_dockerhub_username/app-backend:latest"}' \
          https://your-cloud-platform/api/deploy
