name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - master
      - "**"

jobs:
  # Étape 1 : Tests sur la branche dev
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI tests
        run: |
          pytest --maxfail=5 --disable-warnings

  # Étape 2 : Build Docker et tests sur la branche staging
  build-and-test:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -f backend/Dockerfile -t linkaon/machine_learning_project-backend:staging .
          docker build -f frontend/Dockerfile -t linkaon/machine_learning_project-frontend:staging .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push linkaon/machine_learning_project-backend:staging
          docker push linkaon/machine_learning_project-frontend:staging

      - name: Run integration tests
        run: |
          # Ajouter vos tests d'intégration ici
          echo "Tests d'intégration exécutés."

  # Étape 3 : Déploiement sur la branche main
  deploy:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker images from staging
        run: |
          docker pull linkaon/machine_learning_project-backend:staging
          docker pull linkaon/machine_learning_project-frontend:staging

      - name: Tag images as latest
        run: |
          docker tag linkaon/machine_learning_project-backend:staging linkaon/machine_learning_project-backend:latest
          docker tag linkaon/machine_learning_project-frontend:staging linkaon/machine_learning_project-frontend:latest

      - name: Push Docker images to main
        run: |
          docker push linkaon/machine_learning_project-backend:latest
          docker push linkaon/machine_learning_project-frontend:latest
  
      - name: Debug Docker login
        run: |
          echo "Logging in to Docker Hub..."
          docker info
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Cloud
        run: |
          echo "Déploiement terminé avec succès. Ajouter ici votre commande ou API de déploiement cloud."
